feat: Enhance k8s-operator build workflow with versioning, testing, and manifest verification

diff --git a/.github/workflows/build_k8s_operator.yaml b/.github/workflows/build_k8s_operator.yaml
--- a/.github/workflows/build_k8s_operator.yaml
+++ b/.github/workflows/build_k8s_operator.yaml
@@ -9,3 +9,70 @@ on:
 jobs:
   build:
     runs-on: ubuntu-latest
+    env:
+      IMAGE: gcp-symphony-operator
+      REGISTRY: "gcp-symphony-registry" # TODO: Update with actual registry
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - name: Check Tag
+        id: check-tag
+        run: |
+          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+              echo "match=true" >> $GITHUB_OUTPUT
+          fi
+
+      - name: Set version on a valid SemVer tag
+        if: steps.check-tag.outputs.match == 'true'
+        run: |
+          # Extract the version part (e.g., 1.2.3)
+          echo "VERSION=$(echo "${{ github.ref_name }}" | sed 's/^v//')" >> $GITHUB_ENV
+
+      - name: Set version on any other tag
+        if: steps.check-tag.outputs.match != 'true'
+        run: echo "VERSION=1.0.0" >> $GITHUB_ENV
+
+      - name: Add a directory to the PATH
+        run: echo "/usr/bin" >> $GITHUB_PATH
+
+      - name: Run tests
+        run: |
+          cd k8s-operator
+          curl -LsSf https://astral.sh/uv/install.sh | sh
+          uv venv
+          source .venv/bin/activate
+          uv pip install -e ".[dev]"
+          pytest tests
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v1
+
+      - name: Build Docker image
+        uses: docker/build-push-action@v2
+        with:
+          context: k8s-operator
+          file: ./k8s-operator/Dockerfile
+          push: false
+          load: true
+          tags: |
+            ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ env.VERSION }}
+            ${{ env.REGISTRY }}/${{ env.IMAGE }}:latest
+
+      - name: Run export-manifests
+        run: |
+          docker run --rm ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ env.VERSION }} export-manifests > manifests.yaml
+
+      - name: Verify manifests
+        run: |
+          if [ -f k8s-operator/tests/manifests/gcp-symphony-operator.yaml.j2 ]; then
+            diff manifests.yaml k8s-operator/tests/manifests/gcp-symphony-operator.yaml.j2 || { echo "Manifest mismatch manifests.yaml and k8s-operator/tests/manifests/gcp-symphony-operator.yaml.j2"; exit 1; }
+          else
+            echo "k8s-operator/gcp-symphony-operator.yaml.j2 not found." && exit 1
+          fi
+      # Defer for now until we have a registry to push to
+      # - name: Push Docker Image
+      #   run: |
+      #     docker push ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ env.VERSION }} && docker push ${{ env.REGISTRY }}/${{ env.IMAGE }}:latest
+      
+      
